version: '3.8'

#to run: docker-compose up --build

services:
  node1:
    build:
      context: .
      dockerfile: docker-container-chord
    container_name: chord-node-1-tls
    hostname: node1
    networks:
      - chord_network
    ports:
      - "5000:4000"
    command: >
      -a node1
      -p 4000
      --ts 3000
      --tff 1000
      --tcp 3000
      -r 3
      --tls
    stdin_open: true
    tty: true

  node2:
    build:
      context: .
      dockerfile: docker-container-chord
    container_name: chord-node-2-tls
    hostname: node2
    networks:
      - chord_network
    ports:
      - "5010:4000"
    depends_on:
      - node1
    command: >
      -a node2
      -p 4000
      --ja node1
      --jp 4000
      --ts 3000
      --tff 1000
      --tcp 3000
      -r 3
      --tls
    stdin_open: true
    tty: true

  node3:
    build:
      context: .
      dockerfile: docker-container-chord
    container_name: chord-node-3-tls
    hostname: node3
    networks:
      - chord_network
    ports:
      - "5020:4000"
    depends_on:
      - node1
    command: >
      -a node3
      -p 4000
      --ja node1
      --jp 4000
      --ts 3000
      --tff 1000
      --tcp 3000
      -r 3
      --tls
    stdin_open: true
    tty: true

  node4:
    build:
      context: .
      dockerfile: docker-container-chord
    container_name: chord-node-4-tls
    hostname: node4
    networks:
      - chord_network
    ports:
      - "5030:4000"
    depends_on:
      - node1
    command: >
      -a node4
      -p 4000
      --ja node1
      --jp 4000
      --ts 3000
      --tff 1000
      --tcp 3000
      -r 3
      --tls
    stdin_open: true
    tty: true

  node5:
    build:
      context: .
      dockerfile: docker-container-chord
    container_name: chord-node-5-tls
    hostname: node5
    networks:
      - chord_network
    ports:
      - "5040:4000"
    depends_on:
      - node1
    command: >
      -a node5
      -p 4000
      --ja node1
      --jp 4000
      --ts 3000
      --tff 1000
      --tcp 3000
      -r 3
      --tls
    stdin_open: true
    tty: true

  node6:
    build:
      context: .
      dockerfile: docker-container-chord
    container_name: chord-node-6-tls
    hostname: node6
    networks:
      - chord_network
    ports:
      - "5060:4000"
    depends_on:
      - node1
    command: >
      -a node6
      -p 4000
      --ja node1
      --jp 4000
      --ts 3000
      --tff 1000
      --tcp 3000
      -r 3
      --tls
    stdin_open: true
    tty: true

  node7:
    build:
      context: .
      dockerfile: docker-container-chord
    container_name: chord-node-7-tls
    hostname: node7
    networks:
      - chord_network
    ports:
      - "5070:4000"
    depends_on:
      - node1
    command: >
      -a node7
      -p 4000
      --ja node1
      --jp 4000
      --ts 3000
      --tff 1000
      --tcp 3000
      -r 3
      --tls
    stdin_open: true
    tty: true

  node8:
    build:
      context: .
      dockerfile: docker-container-chord
    container_name: chord-node-8-tls
    hostname: node8
    networks:
      - chord_network
    ports:
      - "5080:4000"
    depends_on:
      - node1
    command: >
      -a node8
      -p 4000
      --ja node1
      --jp 4000
      --ts 3000
      --tff 1000
      --tcp 3000
      -r 3
      --tls
    stdin_open: true
    tty: true

networks:
  chord_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
